# Docker Compose does not support Flask and Node as a service combination so only the user facing Flask will be composed properly.
# Node will be accessed using localhost, not the service name

version: '3'
services:
  node:
    build: ./src/node
    ports:
      - '3000:3000'
  flask:
    build: ./src
    ports:
      - '80:80'
    depends_on:
      - node